from __future__ import annotations

import json
from pathlib import Path

from .analyzer import AnalysisReport, UNIT_NORMALIZATION_MAP


def write_json_report(report: AnalysisReport, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(report.to_dict(), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def write_markdown_report(report: AnalysisReport, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    cls_units = _format_counter(report.classification_unit_variants, limit=15)
    price_units = _format_counter(report.price_unit_variants, limit=15)
    divisions = "\n".join(
        f"| `{code}` | {report.work_division_names.get(code, '-')} | {count:,} |"
        for code, count in sorted(report.work_division_counts.items())
    )
    hierarchy_levels = "\n".join(
        f"| Level {level} | {count:,} |"
        for level, count in sorted(report.unique_hierarchy_paths_by_level.items())
    )
    quality_issues = "\n".join(f"- {issue}" for issue in report.data_quality_issues)
    implications = "\n".join(f"- {item}" for item in report.design_implications)
    unit_map = "\n".join(
        f"| `{raw}` | `{canonical}` |"
        for raw, canonical in sorted(UNIT_NORMALIZATION_MAP.items())
    )
    unmapped = ", ".join(f"`{unit}`" for unit in report.unmapped_units[:20])
    if len(report.unmapped_units) > 20:
        unmapped += f", ... (+{len(report.unmapped_units) - 20} more)"

    markdown = f"""# Phase 1 Data Analysis Report

> Auto-generated by `python -m src.run_phase1_analysis`.
> Re-run the script after dataset changes to refresh these numbers.

## Dataset Overview

| Metric | Value |
|--------|------:|
| Classification rows | {report.classification_rows:,} |
| Price rows | {report.price_rows:,} |
| Hierarchy-only rows (no item code) | {report.hierarchy_only_rows:,} |
| Leaf item rows | {report.leaf_item_rows:,} |
| Unique item codes in classification | {report.unique_classification_codes:,} |
| Unique item codes in price | {report.unique_price_codes:,} |
| Codes with price | {report.codes_with_price:,} |
| Codes without price | {report.codes_without_price:,} |
| Codes only in price | {report.codes_only_in_price:,} |
| Duplicate item codes in classification | {report.duplicate_classification_codes:,} |
| Duplicate item codes in price | {report.duplicate_price_codes:,} |
| Price rows with all zero cost components | {report.all_zero_price_rows:,} |

## Work Division Distribution

| Code | Name | Rows |
|------|------|-----:|
{divisions}

## Hierarchy Shape

| Level | Unique code paths |
|-------|------------------:|
{hierarchy_levels}

## Unit Variants

### Classification dataset (top variants)

| Unit | Count |
|------|------:|
{cls_units}

### Price dataset (top variants)

| Unit | Count |
|------|------:|
{price_units}

### Proposed canonical unit mapping (Phase 1 draft)

| Raw value | Canonical value |
|-----------|-----------------|
{unit_map}

Unmapped units requiring manual review: {unmapped or "None"}

## Sample Records

### Hierarchy-only row

```json
{json.dumps(report.sample_hierarchy_only_row, ensure_ascii=False, indent=2)}
```

### Item without price

```json
{json.dumps(report.sample_item_without_price, ensure_ascii=False, indent=2)}
```

### Item with price

```json
{json.dumps(report.sample_item_with_price, ensure_ascii=False, indent=2)}
```

## Data Quality Issues

{quality_issues}

## Design Implications for Phase 2+

{implications}
"""

    output_path.write_text(markdown, encoding="utf-8")


def _format_counter(values: dict[str, int], limit: int = 10) -> str:
    ranked = sorted(values.items(), key=lambda item: item[1], reverse=True)
    rows = [f"| `{unit or '(empty)'}` | {count:,} |" for unit, count in ranked[:limit]]
    return "\n".join(rows) if rows else "| - | - |"
